"""plane mappings

Revision ID: 22f2c570f81f
Revises: bf64e81c963c
Create Date: 2026-07-06 19:44:37.619161
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "22f2c570f81f"
down_revision: str | None = "bf64e81c963c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_mappings",
        sa.Column("plane_project_id", sa.String(length=64), nullable=False),
        sa.Column("repo", sa.String(length=255), nullable=False),
        sa.Column("base_branch", sa.String(length=255), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("plane_project_id"),
    )
    op.create_table(
        "state_mappings",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("plane_project_id", sa.String(length=64), nullable=False),
        sa.Column("workflow_state", sa.String(length=32), nullable=False),
        sa.Column("plane_state_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plane_project_id", "workflow_state"),
    )
    op.create_index(
        op.f("ix_state_mappings_plane_project_id"),
        "state_mappings",
        ["plane_project_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_state_mappings_plane_project_id"), table_name="state_mappings")
    op.drop_table("state_mappings")
    op.drop_table("project_mappings")
    # ### end Alembic commands ###
